version: "3.5"

#docker build --platform=linux/amd64 -t newtonn2211/slackbotmattermost-slack_bot_service_amd64:latest .
#docker push newtonn2211/slackbotmattermost-slack_bot_service_amd64

services:

  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - slack_bot_service
    ports:
      - "8082:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - custom

  slack_bot_service:
    #image: newtonn2211/slackbotmattermost-slack_bot_service:latest
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "3005:3006"
    volumes:
      - "/Users/olegtetenev/Public/settings.ini:/var/app/slackbot_mattermost/settings.ini"
      - "/Users/olegtetenev/Public/config.json:/var/app/slackbot_mattermost/config.json"
      - "/Users/olegtetenev/Public/log:/var/app/slackbot_mattermost/log"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "version=1.0.0"
    deploy:
      replicas: 1
    image: newtonn2211/slackbotmattermost-slack_bot_service:dm
    networks:
      - custom
networks:
 custom:
   driver: bridge